baseURL = "https://nhittt29.github.io/MyTechTales/"
languageCode = "vi"
title = "My Tech Tales"
theme = "PaperMod"

# Pagination
[pagination]
  pagerSize = 5

# Menu chính
[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

  [[menu.main]]
    name = "Blog"
    url = "/blog/"
    weight = 2

  [[menu.main]]
    name = "Profile"
    url = "/profile/"
    weight = 3

  [[menu.main]]
    name = "Tìm kiếm"
    url = "/search/"
    weight = 4

# Cấu hình chung
[params]
  # Hiển thị tính năng nâng cao của PaperMod
  ShowReadingTime = true
  ShowBreadCrumbs = true
  ShowPostNavLinks = true
  ShowCodeCopyButtons = true
  ShowToc = true
  layout = "cards"
  ShowPostsOnHome = false
  ShowCover = false

  # Tùy chỉnh CSS (quan trọng)
  customCSS = [
    "css/custom.css",   # đường dẫn tương đối từ /static/
    "css/profile.css"
  ]

  # Cho phép bài viết tương lai
  future = true
  
  # Ẩn footer mặc định
  hideFooter = true

# Cấu hình ảnh bìa
[params.cover]
  linkFullImages = true
  relative = false
  hidden = false
  hiddenInList = false
  hiddenInSingle = false
  responsiveImages = false

# Cấu hình xuất đầu ra
[outputs]
  home = ["HTML", "RSS", "JSON"]

# Cấu hình build dành cho GitHub Pages
[markup]
  [markup.goldmark.renderer]
    unsafe = true   # ⚠️ Bắt buộc nếu bạn dùng inline HTML trong Markdown (ví dụ <img>, <div>)
