baseURL = "https://nhittt29.github.io/MyTechTales/"
languageCode = "vi"
title = "MyTechTales"
theme = "PaperMod"

[pagination]
  pagerSize = 5

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

  [[menu.main]]
    name = "Blog"
    url = "/blog/"
    weight = 2

  [[menu.main]]
    name = "Profile"
    url = "/profile/"
    weight = 3

[params]
  ShowReadingTime = true
  ShowBreadCrumbs = true
  ShowPostNavLinks = true
  ShowCodeCopyButtons = true
  ShowToc = true
  layout = "cards"
  ShowPostsOnHome = false
  ShowCover = true  # Thêm dòng này để bật hiển thị ảnh bìa

  [params.cover]
    linkFullImages = true
    relative = true
    hidden = false
    hiddenInList = false
    hiddenInSingle = false