baseURL = "https://nhittt29.github.io/MyTechTales/"
languageCode = "vi"
title = "My Tech Tales"
theme = "PaperMod"

[pagination]
  pagerSize = 5

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

  [[menu.main]]
    name = "Blog"
    url = "/blog/"
    weight = 2

  [[menu.main]]
    name = "Profile"
    url = "/profile/"
    weight = 3

  [[menu.main]]
    name = "Tìm kiếm"
    url = "/search/"
    weight = 4   # thêm menu search ở vị trí thứ 4

[params]
  ShowReadingTime = true
  ShowBreadCrumbs = true
  ShowPostNavLinks = true
  ShowCodeCopyButtons = true
  ShowToc = true
  layout = "cards"
  ShowPostsOnHome = false
  ShowCover = false

  # Thêm các file CSS tùy chỉnh
  customCSS = [
    "/css/custom.css",
    "/css/profile.css"
  ]

  # Cho phép hiển thị bài viết có ngày trong tương lai
  future = true
  
  # Ẩn footer mặc định của PaperMod
  hideFooter = true

[params.cover]
  linkFullImages = true
  relative = false
  hidden = false
  hiddenInList = false
  hiddenInSingle = false
  responsiveImages = false

[outputs]
  home = ["HTML", "RSS", "JSON"]
